name: Deploy Django App

on:
  push:
    branches:
      - main  # main 브랜치에 새로운 커밋이 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Debug Environment
        run: env


      - name: Set up SSH agent and add private key
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          echo "$DEPLOY_KEY" > id_rsa
          chmod 600 id_rsa
          eval "$(ssh-agent -s)"
          ssh-add id_rsa
          ssh-keyscan -H ${{ secrets.DEPLOY_SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        env:
          SERVER_IP: ${{ secrets.DEPLOY_SERVER_IP }}
          SERVER_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          ssh $SERVER_USER@$SERVER_IP << 'EOF'
            cd C:/Users/muneo/smartfarm_monitoring  # Django 프로젝트 디렉토리로 이동
            source /opt/conda/etc/profile.d/conda.sh  # Conda 환경 활성화를 위한 스크립트 로드
            conda activate yolo  # Conda 가상환경 활성화
            git pull origin main  # 최신 변경사항 가져오기
            pip install -r requirements.txt  # 필요시 패키지 업데이트
            python manage.py migrate  # 데이터베이스 마이그레이션
            python manage.py collectstatic --noinput  # 정적 파일 수집
            sudo systemctl restart gunicorn  # Gunicorn이나 WSGI 서버 재시작
            sudo systemctl restart nginx  # 필요시 Nginx 재시작
          EOF
