name: Fetch Cropping Season Data

on:
  schedule:
    - cron: '*/10 * * * *'  # 10분마다 실행
  workflow_dispatch:  # 수동으로도 실행할 수 있도록 설정

jobs:
  fetch_cropping_season_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pytz

      - name: Fetch Cropping Season Data
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}  # GitHub Secrets에서 서비스 키 가져오기
        run: python .github/fetch_cropping_season_data.py  # Python 스크립트 실행

      - name: Commit and push weather data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "muneo"
          git config --global user.email "muneo4195@naver.com"
          git add data/cropping_season_data.json
          git commit -m "Update cropping season data"
          git push
