name: Fetch Identity Data

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  fetch_identity_data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch Identity Data
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}  # GitHub Secrets에서 서비스 키 가져오기
        run: python fetch_identity_data.py  # Python 스크립트 실행

      - name: Commit and push identity data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "muneo"
          git config --global user.email "muneo4195@naver.com"
          git add data/identity_data.json
          git commit -m "Update identity_data"
          git push
